//
//  This was auto-generated by make_bridge.rb
//  Created by 田中 達也 on 2016/10/03.
//  Copyright © 2016年 tattn. All rights reserved.
//

import UIKit
import JavaScriptCore

@objc protocol JSUIColor: JSExport {
    static func __halfTransparentBlackColor() -> UIColor
    static func __halfTransparentWhiteColor() -> UIColor
    static func _accessibilityButtonShapesBackgroundColorOnDark() -> UIColor
    static func _accessibilityButtonShapesBackgroundColorOnLight() -> UIColor
    static func _accessibilityButtonShapesDisabledBackgroundColorOnDark() -> UIColor
    static func _accessibilityButtonShapesNoBlendModeBackgroundColorOnDark() -> UIColor
    static func _accessibilityButtonShapesNoBlendModeBackgroundColorOnLight() -> UIColor
    static func _alternateSystemInteractionTintColor() -> UIColor
    static func _barHairlineShadowColor() -> UIColor
    static func _barStyleBlackHairlineShadowColor() -> UIColor
    static func _composedColorFromSourceColor(arg1: UIColor, arg2: UIColor, arg3: UIColor, arg4: Double) -> UIColor
    static func _dimmingViewColor() -> UIColor
    static func _disambiguated_due_to_CIImage_colorWithCGColor(arg1: CGColor) -> UIColor
    static func _disambiguated_due_to_CIImage_colorWithRed(arg1: Double, arg2: Double, arg3: Double, arg4: Double) -> UIColor
    static func _externalBarBackgroundColor() -> UIColor
    static func _externalSystemDarkGrayColor() -> UIColor
    static func _externalSystemExtraDarkGrayColor() -> UIColor
    static func _externalSystemGrayColor() -> UIColor
    static func _externalSystemMidGrayColor() -> UIColor
    static func _externalSystemSuperDarkGrayColor() -> UIColor
    static func _externalSystemWhiteColor() -> UIColor
    static func _grayColorForFontSize(arg1: Double) -> UIColor
    static func _luminanceWithRed(arg1: Double, arg2: Double, arg3: Double) -> Double
    static func _markedTextBackgroundColor() -> UIColor
    static func _markedTextBorderColor() -> UIColor
    static func _systemColorForColor(arg1: UIColor, arg2: UIColor) -> UIColor
    static func _systemColorWithName(arg1: UIColor) -> UIColor
    static func _systemDestructiveTintColor() -> UIColor
    static func _systemInteractionTintColor() -> UIColor
    static func _systemMidGrayTintColor() -> UIColor
    static func _systemSelectedColor() -> UIColor
    static func _translucentPaperTextureColor() -> UIColor
    static func _vibrantDarkFillDodgeColor() -> UIColor
    static func _vibrantLightDividerBurnColor() -> UIColor
    static func _vibrantLightDividerDarkeningColor() -> UIColor
    static func _vibrantLightFillBurnColor() -> UIColor
    static func _vibrantLightFillDarkeningColor() -> UIColor
    static func _vibrantLightSectionDelimiterDividerBurnColor() -> UIColor
    static func _vibrantLightSectionDelimiterDividerDarkeningColor() -> UIColor
    static func _webContentBackgroundColor() -> UIColor
    static func blackColor() -> UIColor
    static func blueColor() -> UIColor
    static func brownColor() -> UIColor
    static func classFallbacksForKeyedArchiver() -> UIColor
    static func clearColor() -> UIColor
    static func colorWithCGColor(arg1: CGColor) -> UIColor
    static func colorWithCIColor(arg1: UIColor) -> UIColor
    static func colorWithDisplayP3Red(arg1: Double, arg2: Double, arg3: Double, arg4: Double) -> UIColor
    static func colorWithHue(arg1: Double, arg2: Double, arg3: Double, arg4: Double) -> UIColor
    static func colorWithPatternImage(arg1: UIColor) -> UIColor
    static func colorWithRed(arg1: Double, arg2: Double, arg3: Double, arg4: Double) -> UIColor
    static func colorWithWhite(arg1: Double, arg2: Double) -> UIColor
    static func cyanColor() -> UIColor
    static func darkGrayColor() -> UIColor
    static func darkTextColor() -> UIColor
    static func externalSystemGreenColor() -> UIColor
    static func externalSystemRedColor() -> UIColor
    static func externalSystemTealColor() -> UIColor
    static func grayColor() -> UIColor
    static func greenColor() -> UIColor
    static func groupTableViewBackgroundColor() -> UIColor
    static func infoTextOverPinStripeTextColor() -> UIColor
    static func initialize()
    static func insertionPointColor() -> UIColor
    static func lightGrayColor() -> UIColor
    static func lightTextColor() -> UIColor
    static func magentaColor() -> UIColor
    static func noContentDarkGradientBackgroundColor() -> UIColor
    static func noContentLightGradientBackgroundColor() -> UIColor
    static func orangeColor() -> UIColor
    static func pinStripeColor() -> UIColor
    static func purpleColor() -> UIColor
    static func redColor() -> UIColor
    static func scrollViewTexturedBackgroundColor() -> UIColor
    static func sectionHeaderBackgroundColor() -> UIColor
    static func sectionHeaderBorderColor() -> UIColor
    static func sectionHeaderOpaqueBackgroundColor() -> UIColor
    static func sectionListBorderColor() -> UIColor
    static func selectionGrabberColor() -> UIColor
    static func selectionHighlightColor() -> UIColor
    static func supportsSecureCoding() -> Bool
    static func systemBlueColor() -> UIColor
    static func systemDarkBlueColor() -> UIColor
    static func systemDarkGreenColor() -> UIColor
    static func systemDarkOrangeColor() -> UIColor
    static func systemDarkPinkColor() -> UIColor
    static func systemDarkRedColor() -> UIColor
    static func systemDarkTealColor() -> UIColor
    static func systemDarkYellowColor() -> UIColor
    static func systemGrayColor() -> UIColor
    static func systemGreenColor() -> UIColor
    static func systemMidGrayColor() -> UIColor
    static func systemOrangeColor() -> UIColor
    static func systemPinkColor() -> UIColor
    static func systemPurpleColor() -> UIColor
    static func systemRedColor() -> UIColor
    static func systemTealColor() -> UIColor
    static func systemYellowColor() -> UIColor
    static func tableBackgroundColor() -> UIColor
    static func tableCellBackgroundColor() -> UIColor
    static func tableCellBlueTextColor() -> UIColor
    static func tableCellDefaultSelectionTintColor() -> UIColor
    static func tableCellGrayTextColor() -> UIColor
    static func tableCellGroupedBackgroundColor() -> UIColor
    static func tableCellGroupedBackgroundColorLegacyWhite() -> UIColor
    static func tableCellPlainBackgroundColor() -> UIColor
    static func tableCellValue1BlueColor() -> UIColor
    static func tableCellValue2BlueColor() -> UIColor
    static func tableCellbackgroundColorCarPlay() -> UIColor
    static func tableGroupedSeparatorLightColor() -> UIColor
    static func tableGroupedTopShadowColor() -> UIColor
    static func tablePlainHeaderFooterBackgroundColor() -> UIColor
    static func tablePlainHeaderFooterFloatingBackgroundColor() -> UIColor
    static func tableSelectionColor() -> UIColor
    static func tableSelectionGradientEndColor() -> UIColor
    static func tableSelectionGradientStartColor() -> UIColor
    static func tableSeparatorDarkColor() -> UIColor
    static func tableSeparatorLightColor() -> UIColor
    static func tableShadowColor() -> UIColor
    static func textFieldAtomBlueColor() -> UIColor
    static func textFieldAtomPurpleColor() -> UIColor
    static func underPageBackgroundColor() -> UIColor
    static func viewFlipsideBackgroundColor() -> UIColor
    static func whiteColor() -> UIColor
    static func yellowColor() -> UIColor
    static func AV_indicatorBackgroundColor() -> UIColor
    static func AV_indicatorForegroundColor() -> UIColor
    static func faceTimeBabyBlueColor() -> UIColor
    static func faceTimeDarkSeparatorColor() -> UIColor
    static func faceTimeLightBabyBlueColor() -> UIColor
    static func faceTimeLightSeparatorColor() -> UIColor
    static func faceTimeSectionOutlineColor() -> UIColor
    static func faceTimeSeparatorColorWithBlurUnsupported() -> UIColor
    static func faceTimeShadowedGroupBackgroundColor() -> UIColor
    static func _cnui_actionBackgroundColor() -> UIColor
    static func _cnui_actionHighlightedBackgroundColor() -> UIColor
    static func _cnui_actionTitleColor() -> UIColor
    static func ab_colorWithR(arg1: Double, arg2: Double, arg3: Double, arg4: Double) -> UIColor
    static func cardBackgroundInPopoverColor() -> UIColor
    static func cardCellBackgroundColor() -> UIColor
    static func cardCellReadonlyBackgroundColor() -> UIColor
    static func cardCellSeparatorColor() -> UIColor
    static func cardLabelReadonlyTextColor() -> UIColor
    static func cardLabelSuggestedTextColor() -> UIColor
    static func cardValueReadonlyTextColor() -> UIColor
    static func cardValueSuggestedTextColor() -> UIColor
    static func cardValueTextColor() -> UIColor
    static func tableViewBackgroundColorOpaque() -> UIColor
    static func _mapkit_colorForTransitLine(arg1: UIColor) -> UIColor
    static func _mapkit_userLocationAccuracyRingFillColor() -> UIColor
    static func _mapkit_userLocationAccuracyRingStrokeColor() -> UIColor
    static func _mapkit_userLocationAccuracyRingStrokeColorSatellite() -> UIColor
    static func _sf_defaultWebContentBackgroundColor() -> UIColor
    static func ss_browserSystemColor() -> UIColor
    static func color(arg1: Double, arg2: Double, arg3: Double, arg4: Double) -> UIColor
    static func colorWithVectorRGBA() -> UIColor
    static func _iAd_colorWithRGBA(arg1: UInt) -> UIColor
    static func akBoxBorderColor() -> UIColor
    static func akBubbleFillColor() -> UIColor
    static func akButtonHoverStateColor() -> UIColor
    static func akColorPickerBlue() -> UIColor
    static func akColorPickerGreen() -> UIColor
    static func akColorPickerOrange() -> UIColor
    static func akColorPickerPurple() -> UIColor
    static func akColorPickerRed() -> UIColor
    static func akColorPickerYellow() -> UIColor
    static func akColorWithCIColor(arg1: UIColor) -> UIColor
    static func akColorWithSRGBRed(arg1: Double, arg2: Double, arg3: Double, arg4: Double) -> UIColor
    static func akColorWithWhite(arg1: Double, arg2: Double) -> UIColor
    static func akRowSeparatorColor() -> UIColor
    static func akSystemBlueColor() -> UIColor
    static func akSystemGreenColor() -> UIColor
    static func akSystemPinkColor() -> UIColor
    static func akSystemPurpleColor() -> UIColor
    static func akSystemRedColor() -> UIColor
    static func akSystemYellowColor() -> UIColor
    static func im_colorWithSRGBDescription(arg1: UIColor) -> UIColor
    static func ak_colorWithServerRGBRepresentation(arg1: UIColor) -> UIColor
    static func cam_lightenColor(arg1: UIColor) -> UIColor
    static func CertUIVerifiedColor() -> UIColor
    static func _cnui_colorFromData(arg1: UIColor) -> UIColor
    static func colorWithHexValue(arg1: UIColor, arg2: UnsafePointer<UInt8>) -> UIColor
    static func fmfOrangeColor() -> UIColor
    static func fu_platterBlueColor() -> UIColor
    static func fu_platterDaliTealColor() -> UIColor
    static func fu_platterGreenColor() -> UIColor
    static func fu_platterOrangeColor() -> UIColor
    static func fu_platterPinkColor() -> UIColor
    static func fu_platterPurpleColor() -> UIColor
    static func fu_platterRedColor() -> UIColor
    static func fu_platterTealBlueColor() -> UIColor
    static func fu_platterWhiteColor() -> UIColor
    static func fu_platterYellowColor() -> UIColor
    static func fu_systemBlueColor() -> UIColor
    static func fu_systemGreenColor() -> UIColor
    static func fu_systemGreyColor() -> UIColor
    static func fu_systemMintColor() -> UIColor
    static func fu_systemOrangeColor() -> UIColor
    static func fu_systemPinkColor() -> UIColor
    static func fu_systemPurpleColor() -> UIColor
    static func fu_systemRedColor() -> UIColor
    static func fu_systemTealBlueColor() -> UIColor
    static func fu_systemTextGreyColor() -> UIColor
    static func fu_systemYellowColor() -> UIColor
    static func hu_keyColor() -> UIColor
    static func hu_vibrantGreenTextColor() -> UIColor
    static func hu_vibrantRedTextColor() -> UIColor
    static func blTableviewBackgroundColor() -> UIColor
    static func colorFromPlist(arg1: UIColor) -> UIColor
    static func colorWithHexString(arg1: UIColor) -> UIColor
    static func iMovieBlueColor() -> UIColor
    static func iMovieDisabledColor() -> UIColor
    static func iMoviePluginTintColor() -> UIColor
    static func iMovieTintColor() -> UIColor
    static func popoverBackgroundColor() -> UIColor
    static func randomColor() -> UIColor
    static func mt_backgroundColor() -> UIColor
    static func mt_cellAccessoryColor() -> UIColor
    static func mt_cellHighlightColor() -> UIColor
    static func mt_cellSeparatorColor() -> UIColor
    static func mt_disabledButtonTintColor() -> UIColor
    static func mt_disabledTextColor() -> UIColor
    static func mt_foregroundColor() -> UIColor
    static func mt_lapResetButtonTextColor() -> UIColor
    static func mt_lapResetButtonTintColor() -> UIColor
    static func mt_pauseButtonTextColor() -> UIColor
    static func mt_pauseButtonTintColor() -> UIColor
    static func mt_primaryColor() -> UIColor
    static func mt_primaryTextColor() -> UIColor
    static func mt_quaternaryColor() -> UIColor
    static func mt_secondaryColor() -> UIColor
    static func mt_secondaryTextColor() -> UIColor
    static func mt_sleepColor() -> UIColor
    static func mt_startResumeButtonTextColor() -> UIColor
    static func mt_startResumeButtonTintColor() -> UIColor
    static func mt_stopButtonTextColor() -> UIColor
    static func mt_stopButtonTintColor() -> UIColor
    static func mt_stopwatchMajorTickMarkColor() -> UIColor
    static func mt_stopwatchMinorTickMarkColor() -> UIColor
    static func mt_tertiaryColor() -> UIColor
    static func mt_tintColor() -> UIColor
    static func mt_wakeColor() -> UIColor
    static func mt_worldClockMapLandColor() -> UIColor
    static func colorWithWebColor(arg1: UIColor) -> UIColor
    static func colorWithWebColorName(arg1: UIColor) -> UIColor
    static func colorWithWebHexTriplet(arg1: UIColor) -> UIColor
    static func colorWithWebRgb(arg1: UIColor) -> UIColor
    static func fc_colorWithHexString(arg1: UIColor) -> UIColor
    static func fc_colorWithHue(arg1: Double, arg2: Double, arg3: Double, arg4: Double) -> UIColor
    static func ICDarkenedTintColor() -> UIColor
    static func ICGrayColor() -> UIColor
    static func ICGrayTodoButtonColor() -> UIColor
    static func ICGrayTodoButtonHighlightColor() -> UIColor
    static func ICLearnMoreButtonPressedColor() -> UIColor
    static func ICLearnMoreButtonUnpressedColor() -> UIColor
    static func ICListStatusIndicatorColor() -> UIColor
    static func ICLockIconColor() -> UIColor
    static func ICLockIconColorList() -> UIColor
    static func ICRedColor() -> UIColor
    static func ICTintColor() -> UIColor
    static func ICTintedSelectionColor() -> UIColor
    static func ICYellowTodoButtonColor() -> UIColor
    static func ICYellowTodoButtonHighlightColor() -> UIColor
    static func ic_colorWith256Red(arg1: Double, arg2: Double, arg3: Double, arg4: Double) -> UIColor
    static func preferredDefaultFontColor() -> UIColor
    static func checkerboardColorWithColor(arg1: UIColor, arg2: UIColor, arg3: CGSize) -> UIColor
    static func grayCheckerboardColor() -> UIColor
    static func tableViewCellDarkBlueTextColor() -> UIColor
    static func transparentGrayCheckerboardColor() -> UIColor
    static func colorWithPKColor(arg1: UIColor) -> UIColor
    static func pr_backgroundColor() -> UIColor
    static func pr_darkAccentColor() -> UIColor
    static func pr_lightAccentColor() -> UIColor
    static func alternateSelectedControlColor() -> UIColor
    static func _remoteUI_colorWithString(arg1: UIColor) -> UIColor
    static func safari_colorWithRGBColorComponents(arg1: UIColor) -> UIColor
    static func safari_colorWithSerializedColorData(arg1: UIColor) -> UIColor
    static func siriui_glyphColor() -> UIColor
    static func siriui_highlightColor() -> UIColor
    static func siriui_keylineColor() -> UIColor
    static func siriui_keylineColorStark() -> UIColor
    static func siriui_maskingColor() -> UIColor
    static func siriui_maskingHighlightColor() -> UIColor
    static func siriui_platterGlyphColor() -> UIColor
    static func siriui_platterKeylineColor() -> UIColor
    static func siriui_platterSemiTransparentTextColor() -> UIColor
    static func siriui_platterTextColor() -> UIColor
    static func siriui_platterTextHighlightColor() -> UIColor
    static func siriui_primaryTextColor() -> UIColor
    static func siriui_secondaryTextColor() -> UIColor
    static func siriui_semiTransparentTextColor() -> UIColor
    static func siriui_snippetBackgroundColor() -> UIColor
    static func siriui_textColor() -> UIColor
    static func siriui_textHighlightColor() -> UIColor
    static func colorWithStyleString(arg1: UIColor) -> UIColor
    static func tsu_darkInsertSwatchBackgroundColor() -> UIColor
    static func tsu_insertPaneBackgroundColor() -> UIColor
    static func tsu_keynoteCanvasBackgroundColor() -> UIColor
    static func tsu_keynoteCanvasDarkBackgroundColor() -> UIColor
    static func tsu_keynoteDefaultApplicationToolbarTitleColor() -> UIColor
    static func tsu_keynoteNavigationBarBackgroundColor() -> UIColor
    static func tsu_keynoteNavigatorBackgroundColor() -> UIColor
    static func tsu_keynoteNavigatorDividerColor() -> UIColor
    static func tsu_keynoteToolbarTintColor() -> UIColor
    static func tsu_navigatorSelectionFocusedHighlightColor() -> UIColor
    static func tsu_navigatorSelectionHighlightColor() -> UIColor
    static func tsu_progressViewTintColor() -> UIColor
    static func tsu_progressViewTrackTintColor() -> UIColor
    static func tsu_rowItemDividersColor() -> UIColor
    static func tsu_sidebarActiveTintColor() -> UIColor
    static func tsu_sidebarBackgroundColor() -> UIColor
    static func tsu_sidebarCellBackgroundColor() -> UIColor
    static func tsu_sidebarInactiveCellTintColor() -> UIColor
    static func tsu_sidebarInactiveTintColor() -> UIColor
    static func tsu_sidebarNavigationBarBackgroundColor() -> UIColor
    static func tsu_sidebarNavigationBarTintColor() -> UIColor
    static func tsu_sidebarNavigationBarTitleColor() -> UIColor
    static func tsu_sidebarPlaybackButtonTintColor() -> UIColor
    static func tsu_sidebarPressedStateColor() -> UIColor
    static func tsu_sidebarPrimaryContentColor() -> UIColor
    static func tsu_sidebarSecondaryContentColor() -> UIColor
    static func tsu_sidebarSegmentedCellTintColor() -> UIColor
    static func tsu_sidebarSegmentedControlTintColor() -> UIColor
    static func tsu_sidebarTableViewCellTintColor() -> UIColor
    static func tsu_sidebarTopTabTextColor() -> UIColor
    static func tsu_sliderMaximumTrackTintColor() -> UIColor
    static func tsu_sliderMinimumTrackTintColor() -> UIColor
    static func tsu_sliderThumbTintColor() -> UIColor
    static func tsu_switchOffOutlineColor() -> UIColor
    static func tsu_switchOnTintColor() -> UIColor
    static func tsu_switchTintColor() -> UIColor
    static func tsu_tableViewCellDarkBlueTextColor() -> UIColor
}
